apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wireguard-hfswms-org
spec:
  secretName: wireguard-hfswms-org-tls
  issuerRef:
    name: letsencrypt-dns-prod
    kind: ClusterIssuer
  dnsNames:
    - wireguard.hfswms.org

