apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: postgres
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistVolumeReclaimPolicy:  Reain
  storageClassName: local-storage
  local:
    path: /var/lib/postgres/data
  nodeAffinity:
  - machExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values: 
      - hfswms
