apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: postgres
spec:
  ports:
    - port: 5432
      name: pg
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:18
          ports:
          - containerPort: 5432
            name: postgres
          envFrom:
          - secretRef:
              name: postgres-secret
          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-storage
          persisentVolumeClaim:
            claimName: postgres-pv-claim
