apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yt-dlp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Adjust based on how many videos you plan to keep
