apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden # Target namespace for the deployment
    server: https://kubernetes.default.svc
  project: default
  sources:
    # Source 1: The remote Helm Chart
    - repoURL: guerzon.github.io
      chart: vaultwarden
      targetRevision: 0.18.0
      helm:
        valueFiles:
          - $values/apps/vaultwarden/values.yaml
    # Source 2: Your Git Repository containing the values.yaml
    - repoURL: github.com/Gsmith2518/hfswms-argo
      targetRevision: main
      ref: values  # This 'ref' matches the '$values' prefix above
  sources:
  - chart: vaultwarden
    repoURL: https://guerzon.github.io/vaultwarden
    targetRevision: 0.20.0 # Pin to a specific chart version
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # Automatically sync any drift from Git
    syncOptions:
    - CreateNamespace=true
